[book]
title = "Vac RFC"
authors = ["Jakub Soko≈Çowski"]
language = "en"
src = "docs"

[output.html]
default-theme = "ayu"
additional-css = ["custom.css"]
additional-js = ["scripts/rfc-index.js"]
git-repository-url = "https://github.com/vacp2p/rfc-index"
